### ISSUE TITLE
Does not compile on 1.11.0-nightly (01411937f 2016-07-01)

### ISSUE THREAD

**Issue by dtolnay** [erickt/rust-quasi#49]
```
error: unresolved import `syntax::ast::TokenTree`. There is no `TokenTree` in `syntax::ast` [--explain E0432]
  --> src/lib.rs:28:25
   |>
28 |> use syntax::ast::{self, TokenTree};
   |>                         ^^^^^^^^^

error: unresolved import `errors::FatalError`. Maybe a missing `extern crate errors`? [--explain E0432]
 --> <syntax macros>:3:51
  |>
3 |> use std :: result :: Result :: { Ok , Err } ; use errors :: FatalError ; match
  |>                                                   ^^^^^^^^^^^^^^^^^^^^
src/lib.rs:138:9: 138:108: note: in this expansion of panictry! (defined in <syntax macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
  --> src/lib.rs:84:14
   |>
84 |>         vec![ast::TokenTree::Token(DUMMY_SP, token::Ident(*self))]
   |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:84:9: 84:67: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
  --> src/lib.rs:90:14
   |>
90 |>         vec![ast::TokenTree::Token(DUMMY_SP, token::Interpolated(token::NtPath(Box::new(self.clone()))))]
   |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:90:9: 90:106: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
  --> src/lib.rs:96:14
   |>
96 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtTy(P(self.clone()))))]
   |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:96:9: 96:98: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:102:14
    |>
102 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtTy(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:102:9: 102:95: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:108:14
    |>
108 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtBlock(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:108:9: 108:98: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:114:14
    |>
114 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtItem(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:114:9: 114:97: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:120:14
    |>
120 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtImplItem(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:120:9: 120:101: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:126:14
    |>
126 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtTraitItem(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:126:9: 126:102: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:160:13
    |>
160 |>             ast::TokenTree::Token(self.span, token::Interpolated(token::NtStmt(P(self.clone()))))
    |>             ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:159:23: 161:10: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:165:22
    |>
165 |>             tts.push(ast::TokenTree::Token(self.span, token::Semi));
    |>                      ^^^^^^^^^^^^^^^^^^^^^

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:174:14
    |>
174 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtExpr(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:174:9: 174:97: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:180:14
    |>
180 |>         vec![ast::TokenTree::Token(self.span, token::Interpolated(token::NtPat(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:180:9: 180:96: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:186:14
    |>
186 |>         vec![ast::TokenTree::Token(DUMMY_SP, token::Interpolated(token::NtArm(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:186:9: 186:95: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:207:35
    |>
207 |> impl_to_tokens_slice! { ast::Ty, [ast::TokenTree::Token(DUMMY_SP, token::Comma)] }
    |>                                   ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:207:1: 207:83: note: in this expansion of impl_to_tokens_slice! (defined in src/lib.rs)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:212:14
    |>
212 |>         vec![ast::TokenTree::Token(DUMMY_SP, token::Interpolated(token::NtMeta(self.clone())))]
    |>              ^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:212:9: 212:96: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:220:16
    |>
220 |>         r.push(ast::TokenTree::Token(self.span, token::Pound));
    |>                ^^^^^^^^^^^^^^^^^^^^^

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:222:20
    |>
222 |>             r.push(ast::TokenTree::Token(self.span, token::Not));
    |>                    ^^^^^^^^^^^^^^^^^^^^^

error: `ast::Delimited` does not name a structure [--explain E0422]
   --> src/lib.rs:224:61
    |>
224 |>         r.push(ast::TokenTree::Delimited(self.span, Rc::new(ast::Delimited {
    |>                                                             ^^^^^^^^^^^^^^

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:224:16
    |>
224 |>         r.push(ast::TokenTree::Delimited(self.span, Rc::new(ast::Delimited {
    |>                ^^^^^^^^^^^^^^^^^^^^^^^^^

error: `ast::Delimited` does not name a structure [--explain E0422]
   --> src/lib.rs:245:58
    |>
245 |>         vec![ast::TokenTree::Delimited(DUMMY_SP, Rc::new(ast::Delimited {
    |>                                                          ^^^^^^^^^^^^^^
src/lib.rs:245:9: 250:13: note: in this expansion of vec! (defined in <std macros>)

error: failed to resolve. Could not find `TokenTree` in `syntax::ast` [--explain E0433]
   --> src/lib.rs:245:14
    |>
245 |>         vec![ast::TokenTree::Delimited(DUMMY_SP, Rc::new(ast::Delimited {
    |>              ^^^^^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:245:9: 250:13: note: in this expansion of vec! (defined in <std macros>)

error: type name `ast::TokenTree` is undefined or not in scope [--explain E0412]
   --> src/lib.rs:332:43
    |>
332 |>     fn parse_tts(&self, s: String) -> Vec<ast::TokenTree>;
    |>                                           ^^^^^^^^^^^^^^ undefined or not in scope
help: you can import it into scope: `use syntax::tokenstream::TokenTree;`.

error: type name `ast::TokenTree` is undefined or not in scope [--explain E0412]
   --> src/lib.rs:361:43
    |>
361 |>     fn parse_tts(&self, s: String) -> Vec<ast::TokenTree> {
    |>                                           ^^^^^^^^^^^^^^ undefined or not in scope
help: you can import it into scope: `use syntax::tokenstream::TokenTree;`.

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:46:1
   |>
46 |> impl<'a, T: ToTokens> ToTokens for &'a T {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:52:1
   |>
52 |> impl<'a, T: ToTokens> ToTokens for &'a [T] {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:60:1
   |>
60 |> impl<T: ToTokens> ToTokens for Vec<T> {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:66:1
   |>
66 |> impl<T: ToTokens> ToTokens for Spanned<T> {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:73:1
   |>
73 |> impl<T: ToTokens> ToTokens for Option<T> {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:82:1
   |>
82 |> impl ToTokens for ast::Ident {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:88:1
   |>
88 |> impl ToTokens for ast::Path {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
  --> src/lib.rs:94:1
   |>
94 |> impl ToTokens for ast::Ty {
   |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:100:1
    |>
100 |> impl ToTokens for P<ast::Ty> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:106:1
    |>
106 |> impl ToTokens for P<ast::Block> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:112:1
    |>
112 |> impl ToTokens for P<ast::Item> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:118:1
    |>
118 |> impl ToTokens for P<ast::ImplItem> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:124:1
    |>
124 |> impl ToTokens for P<ast::TraitItem> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:130:1
    |>
130 |> impl ToTokens for ast::Generics {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:142:1
    |>
142 |> impl ToTokens for ast::WhereClause {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:157:1
    |>
157 |> impl ToTokens for ast::Stmt {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:172:1
    |>
172 |> impl ToTokens for P<ast::Expr> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:178:1
    |>
178 |> impl ToTokens for P<ast::Pat> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:184:1
    |>
184 |> impl ToTokens for ast::Arm {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:192:9
    |>
192 |>         impl ToTokens for [$t] {
    |>         ^
src/lib.rs:207:1: 207:83: note: in this expansion of impl_to_tokens_slice! (defined in src/lib.rs)
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:192:9
    |>
192 |>         impl ToTokens for [$t] {
    |>         ^
src/lib.rs:208:1: 208:43: note: in this expansion of impl_to_tokens_slice! (defined in src/lib.rs)
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:210:1
    |>
210 |> impl ToTokens for P<ast::MetaItem> {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:216:1
    |>
216 |> impl ToTokens for ast::Attribute {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:234:1
    |>
234 |> impl ToTokens for str {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:243:1
    |>
243 |> impl ToTokens for () {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:254:1
    |>
254 |> impl ToTokens for ast::Lit {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:266:1
    |>
266 |> impl ToTokens for bool {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:272:1
    |>
272 |> impl ToTokens for char {
    |> ^
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:293:9
    |>
293 |>         impl ToTokens for $t {
    |>         ^
src/lib.rs:316:1: 316:54: note: in this expansion of impl_to_tokens_int! (defined in src/lib.rs)
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `ToTokens`: [--explain E0119]
   --> src/lib.rs:307:9
    |>
307 |>         impl ToTokens for $t {
    |>         ^
src/lib.rs:322:1: 322:57: note: in this expansion of impl_to_tokens_int! (defined in src/lib.rs)
note: conflicting implementation is here:
  --> src/lib.rs:40:1
   |>
40 |> impl ToTokens for TokenTree {
   |> ^

error: conflicting implementations of trait `IntoWrappedRepeat`: [--explain E0119]
   --> src/lib.rs:280:9
    |>
280 |>         impl IntoWrappedRepeat for $t {
    |>         ^
src/lib.rs:538:1: 538:33: note: in this expansion of impl_wrap_repeat! (defined in src/lib.rs)
note: conflicting implementation is here:
   --> src/lib.rs:280:9
    |>
280 |>         impl IntoWrappedRepeat for $t {
    |>         ^
src/lib.rs:537:1: 537:32: note: in this expansion of impl_wrap_repeat! (defined in src/lib.rs)
```

**Comment by dtolnay** [comment]
Fixed in cb8728f8430dc3820440f829d9e493735494673d.
