### ISSUE TITLE
Does not compile on rustc 1.14.0-nightly (f09420685 2016-10-20)

### ISSUE THREAD

**Issue by dtolnay** [erickt/rust-quasi#61]
```
quasi_codegen$ cargo build --no-default-features
   Compiling aster v0.30.0
   Compiling quasi_codegen v0.22.0
error[E0531]: unresolved tuple struct/variant `token::SpecialVarNt`
   --> src/lib.rs:442:11
    |
442 |         | token::SpecialVarNt(..) => {
    |           ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by dtolnay** [comment]
Fixed in #62.
